[package]
name = "zeroclash-gui"
version.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true
authors.workspace = true
readme.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
zeroclash-core = { workspace = true }

egui = "0.34"
winit = "0.30"
egui-winit = "0.34"
egui-wgpu = "0.34"
wgpu = "27"
log = { workspace = true }
tokio = { workspace = true }
tokio-tungstenite = "0.26"
futures-util = "0.3"
pollster = "0.4"
dark-light = "2"
anyhow = { workspace = true }
dirs-next = "2"
tray-icon = "0.19"
image = { version = "0.25", default-features = false, features = ["png"] }
serde_yaml_ng = { workspace = true }
serde_json = { workspace = true }
global-hotkey = "0.6"

[lints]
workspace = true
