version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Shanghai"
    labels:
      - "dependencies"
      - "rust"
    assignees:
      - "fynntang"
    open-pull-requests-limit: 5
    groups:
      patch-updates:
        patterns:
          - "*"
        update-types:
          - "patch"
    versioning-strategy: lockfile-only

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "Asia/Shanghai"
    labels:
      - "dependencies"
      - "ci"
    assignees:
      - "fynntang"
