[package]
name = "zeroclash"
version.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true
authors.workspace = true
readme.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
zeroclash-ui = { workspace = true }

[build-dependencies]
ureq = { version = "3", default-features = false, features = ["rustls"] }
flate2 = "1"
zip = "2"

[lints]
workspace = true
