[package]
name = "zeroclash-cli"
version.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true
authors.workspace = true
readme.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
zeroclash-core = { workspace = true }
clap = { version = "4", features = ["derive"] }
tokio = { workspace = true }
serde_json = { workspace = true }
serde_yaml_ng = { workspace = true }
anyhow = { workspace = true }
dirs-next = "2"

[lints]
workspace = true
