[package]
name = "zeroclash-core"
version.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true
authors.workspace = true
readme.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
zeroclash-draft = { workspace = true }
zeroclash-logging = { workspace = true }
zeroclash-limiter = { workspace = true }
zeroclash-sysinfo = { workspace = true }
zeroclash-signal = { workspace = true }
zeroclash-i18n = { workspace = true }

parking_lot = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml_ng = { workspace = true }
compact_str = { workspace = true }
reqwest = { workspace = true }
directories = "6"
dirs-next = "2"
tokio-tungstenite = "0.26"
futures-util = "0.3"
notify-rust = "4"
auto-launch = "0.5"
fd-lock = "4"
boa_engine = "0.20"
zip = "2"

[dev-dependencies]
tempfile = "3"

[lints]
workspace = true
