[package]
name = "zeroclash-ui"
version.workspace = true
edition.workspace = true
description.workspace = true
documentation.workspace = true
authors.workspace = true
readme.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
zeroclash-core = { workspace = true }
zeroclash-i18n = { workspace = true }
gpui = { workspace = true }
gpui_platform = { workspace = true }
anyhow = { workspace = true }
log = { workspace = true }
serde_yaml_ng = { workspace = true }
dark-light = "2"
dirs-next = "2"
tray-icon = "0.24"
global-hotkey = "0.8"
arboard = "3"
pollster = "0.4"
serde_json = { workspace = true }
tokio = { workspace = true }

[target.'cfg(target_os = "macos")'.dependencies]
core-graphics = "0.24"
core-foundation = "0.10"
foreign-types-shared = "0.3"

[lints]
workspace = true
